name: Deploy furnished apartments

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: copy filles to Tamaroas server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 4589
          source: "."
          target: "/home/admin/app/furnished_apartments"

      - name: Deploy application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 4589
          script: |
            cd /home/admin/app/furnished_apartments
            docker stop FURNISHED_PARTMENTS || true
            docker rm FURNISHED_PARTMENTS || true
            docker rmi furnished-apartments:V1 || true
            docker build -t furnished-apartments:V1 .
            docker run -d --name FURNISHED_PARTMENTS -p 8282:80 -v /home/admin/app/volumes/furnished_apartments/writable:/var/www/html/writable furnished-apartments:V1